#!/bin/bash

MAX_B=16

#PREFERRED=$MAX_B

sleep 3
while true ; do
	for i in $( seq $MAX_B ) ; do
		for j in $PREFERRED $( awk 'BEGIN {srand(); print int('$MAX_B'*rand())+1}' ) ; do
			case $j in
				(1)  XY="1040 410";;
				(2)  XY="1180 480";;
				
				(3)  XY="760  410";;
				(4)  XY="900  480";;
				(5)  XY="1040 550";;
				(6)  XY="1180 620";;
				
				(7)  XY="620  480";;
				(8)  XY="760  550";;
				(9)  XY="900  620";;
				(10) XY="1040 690";;
				
				(11) XY="480  550";;
				(12) XY="620  620";;
				(13) XY="760  690";;
				(14) XY="900  760";;
				
				(15) XY="480  690";;
				(16) XY="620  760";;
			esac
			xdotool mousemove --sync $XY click 1 # select building
			sleep 1
			xdotool click 1 # Upgrade
			sleep 1
			xdotool click 1 # speed up
			sleep 15
		done
	done
	xdotool mousemove --sync 1276 335 click 1 # kill Kingdom Quest
	sleep 1
done
