#!/bin/bash

#PREFERRED=12

sleep 3
while true ; do
	for i in $( seq 13 ) ; do
		for j in $PREFERRED $( awk 'BEGIN {srand(); print int(12*rand())+1}' ) ; do
			case $j in
				(1)  XY="1040 420";;
				(2)  XY="1180 490";;
				
				(3)  XY="760  420";;
				(4)  XY="900  490";;
				(5)  XY="1040 560";;
				(6)  XY="1180 630";;
				
				(7)  XY="620  490";;
				(8)  XY="760  560";;
				(9)  XY="900  630";;
				(10) XY="1040 700";;
				
				(11) XY="480  560";;
				(12) XY="620  630";;
				
				(13) XY="480  700";;
			esac
			xdotool mousemove --sync $XY click 1 # select building
			sleep 1
			xdotool click 1 # Upgrade
			sleep 1
			xdotool click 1 # speed up
			sleep 15
		done
	done
	xdotool mousemove --sync 1276 335 click 1 # kill Kingdom Quest
	sleep 1
done
