#!/bin/bash

MAX_B=16

#PREFERRED=8

sleep 3

CORR=$( xdotool getmouselocation 2>&1 | sed 's/:/ /g' | awk '/window/ {print $2, $4}' )

while true ; do
	for i in $( seq $MAX_B ) ; do
		for j in $PREFERRED $( awk 'BEGIN {srand(); print int('$MAX_B'*rand())+1}' ) ; do
			case $j in
				(1)  XY=" 0 0";;
				(2)  XY=" 1 0";;
				
				(3)  XY="-1 1";;
				(4)  XY=" 0 1";;
				(5)  XY=" 1 1";;
				(6)  XY=" 2 1";;
				
				(7)  XY="-1 2";;
				(8)  XY=" 0 2";;
				(9)  XY=" 1 2";;
				(10) XY=" 2 2";;
				
				(11) XY="-1 3";;
				(12) XY=" 0 3";;
				(13) XY=" 1 3";;
				(14) XY=" 2 3";;
				
				(15) XY=" 0 4";;
				(16) XY=" 1 4";;
			esac
			XYC=$( echo $XY $CORR | awk '{a=142; print $3+a*($1-$2), $4+a/2.*($1+$2)}' )
			xdotool mousemove --sync $XYC click 1 # select building
			sleep 1.5
			xdotool click 1 # Upgrade
			sleep 3
			xdotool click 1 # speed up
			sleep .5
		done
		sleep .5
	done
	xdotool mousemove --sync 1276 335 click 1 # kill Kingdom Quest
	sleep 1
done

# same row, 1 right: +142 +71
# next row: +142
