#!/bin/sh

VZ_CHROME_BASE=${VZ_HOME}/alt_chrome
VZ_CHOME_PARAMS="--window-size=${VZ_X}","${VZ_Y} ravenmarch.aoshitang.com"

X0=0
X1=$(( $X0 + $VZ_X ))

Y0=0
YXT=$(( $Y0 + $VZ_Y ))

google-chrome --user-data-dir=${VZ_CHROME_BASE}/Irrlicht    --window-position=${X0}","${Y0} ${VZ_CHOME_PARAMS} &
google-chrome --user-data-dir=${VZ_CHROME_BASE}/OuterShadow --window-position=${X1}","${Y0} ${VZ_CHOME_PARAMS} &

export VZ_FIFO=c2x
rm -rf $VZ_FIFO
mkfifo $VZ_FIFO
cnee --record --keyboard > $VZ_FIFO &

xterm -geometry 160x8+${X0}+${YXT} -e ./cnee2xdo &

# Reserve terminal. 
# Need CTRL+Lclick then switch on "secure keyboard" to have keyboard input in xterm as chrome seem to steal it
xterm -geometry 160x8+${X1}+${YXT} &
