#!/bin/bash

cat $VZ_FIFO | awk -F "," 'BEGIN {t=0;} {\
        if ($1==7 && $2 == 2 && $3 == 0 && $4 == 0 && $5 == 0) {\
                if ($6 == 94) {\
                        if ($8-t>200) system("./q2click sync");\
                        t=$8;\
                } else if ($6 == 49) {\
                        if ($8-t>200) system("./q2click nosync");\
                        t=$8;\
                }
                print $0;\
        }\
        if ($1=="###") {\
                b=sub("###,*",". primitives/");\
                system($0);\
        }\
}'

# \ : sync

# ` : nosync

# execute command from primitives (not protected against using ".." to escape that directory
# echo "###,echo aqq" > c2x_IrrOS