#!/bin/bash

if [ $( echo $VZ_LIST | wc -w ) != $(( $VZ_NX * $VZ_NY )) ] ; then
        echo "number mismatch:"
        echo $VZ_LIST" has "$( echo $VZ_LIST | wc -w )" elements"
        echo $VZ_NX" * "$VZ_NY" = "$(( $VZ_NX * $VZ_NY ))" elements expected"
        exit 1
fi

# default chrome size
export VZ_X=1050
export VZ_Y=660

# y-margin for xterms
export VZ_XTERM_Y=130

# config for zombie VNC
export VZ_HOME=${HOME}
HOME=HOME vncserver -geometry $(( $VZ_X * $VZ_NX ))"x"$(( $VZ_Y * $VZ_NY + $VZ_XTERM_Y ))

#ToDo implement kill
while [ ! -e "./.kill" ] ; do
	sleep 5
done
rm ./.kill
ls -l HOME/.vnc
