#!/bin/bash

SYNC=""
if [ $# -ge 1 ] ; then
        SYNC="--sync"
fi

XY=$( xdotool getmouselocation 2>&1 | sed -n '/window/s/x:\(.*\) y:\(.*\) screen.*/\1 \2/p' )
X=$( echo $XY | awk '{print $1}' )
Y=$( echo $XY | awk '{print $2}' )

sleep .5
if [ $X -le $VZ_X -a $Y -le $VZ_Y ] ; then
  for dy in $( seq $(( $VZ_NY - 1 )) -1 0 ) ; do
    for dx in $( seq $(( $VZ_NX - 1 )) -1 0 ) ; do
      xdotool mousemove $SYNC  $(( $X + $dx * $VZ_X )) $(( $Y + $dy * $VZ_Y )) click 1
      echo -n                  $(( $X + $dx * $VZ_X )) $(( $Y + $dy * $VZ_Y )) " "
      sleep .1
    done
  done
  echo
else
  echo "out of browser 1: "$X $Y
fi



