#!/bin/sh

VZ_CHROME_BASE=${VZ_HOME}/alt_chrome
VZ_CHOME_PARAMS="--window-size=${VZ_X}","${VZ_Y} ravenmarch.aoshitang.com"

ix=0
iy=0
for i in $VZ_LIST; do
        google-chrome --user-data-dir=${VZ_CHROME_BASE}/${i} --window-position=$(( $ix * $VZ_X ))","$(( $iy * $VZ_Y )) ${VZ_CHOME_PARAMS} &
        ix=$(( $ix + 1 ))
        if [ $ix -ge $VZ_NX ] ; then
                ix=0
                iy=$(( $iy + 1 ))
        fi
done

rm -rf $VZ_FIFO
mkfifo $VZ_FIFO
cnee --record --keyboard > $VZ_FIFO &

YXT=$(( $VZ_Y * $VZ_NY ))
xterm -geometry 160x8+$(( 0 * $VZ_X ))+${YXT} -e ./cnee2xdo &

# Reserve terminal. 
# Need CTRL+Lclick then switch on "secure keyboard" to have keyboard input in xterm as chrome seem to steal it
xterm -geometry 160x8+$(( 1 * $VZ_X ))+${YXT} &
