#!/bin/bash

cat $VZ_FIFO | awk -F "," '{\
        if ($1==7 && $2 == 2 && $3 == 0 && $4 == 0 && $5 == 0) {\
                if ($6 == 52)\
                        system("./q2click sync");\
                else if ($6 ==65) \
                        system("./q2click nosync");\
                print $0;\
        }\
}'

# Z : sync
# space : nosync
